# Runs tests to verify:
# 1. All linters are specified in the README.md
# 2. All linters have test coverage.
# 3. Plugin has a healthy composite config
name: Repo Tests
on:
  workflow_call:
    inputs:
      cli-version:
        required: false
        type: string
      cli-path:
        required: false
        type: string

permissions:
  contents: read
  statuses: read

jobs:
  plugins_test:
    name: Plugin Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run repo tests
        run: npm test tests/repo_tests --ci
        env:
          JEST_SUITE_NAME: Repo Tests
          PLUGINS_TEST_CLI_VERSION: ${{ inputs.cli-version }}
          PLUGINS_TEST_CLI_PATH: ${{ inputs.cli-path }}
