# Runs tests to verify:
# 1. All linters are specified in the readme.md
# 2. All linters have test coverage.
# 3. Plugin has a healthy composite config
name: Repo Tests
on:
  workflow_call:
    inputs:
      cli-version:
        required: false
        type: string
      cli-path:
        required: false
        type: string

permissions: read-all

jobs:
  plugins_test:
    name: Plugin Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run repo tests
        run: npm test --ci tests/repo_tests
        env:
          PLUGINS_TEST_CLI_VERSION: ${{ inputs.cli-version }}
          PLUGINS_TEST_CLI_PATH: ${{ inputs.cli-path }}
