# Runs tests to verify:
# 1. All linters are specified in the README.md
# 2. All linters have test coverage.
# 3. Plugin has a healthy composite config
name: Repo Tests
on:
  workflow_call:
    inputs:
      cli-version:
        required: false
        type: string
      cli-path:
        required: false
        type: string

permissions: read-all

jobs:
  plugins_test:
    name: Plugin Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Setup node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run repo tests
        run: npm test --ci tests/repo_tests
        env:
          PLUGINS_TEST_CLI_VERSION: ${{ inputs.cli-version }}
          PLUGINS_TEST_CLI_PATH: ${{ inputs.cli-path }}
