# Runs tests to verify:
# 1. All linters are specified in the README.md
# 2. All linters have test coverage.
# 3. Plugin has a healthy composite config
name: Repo Tests
on:
  workflow_call:
    inputs:
      cli-version:
        required: false
        type: string
      cli-path:
        required: false
        type: string

permissions:
  contents: read
  statuses: read

jobs:
  plugins_test:
    name: Plugin Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run repo tests
        run: npm test tests/repo_tests --ci
        env:
          PLUGINS_TEST_CLI_VERSION: ${{ inputs.cli-version }}
          PLUGINS_TEST_CLI_PATH: ${{ inputs.cli-path }}
